PaddyMonitoring/website/models.py
# Define database models

from . import db

class Profile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    initial_date = db.Column(db.DateTime)
    name_plant = db.Column(db.String(120))
    type_plant = db.Column(db.String(120))
    device = db.Column(db.String(120))
    # Create relationship
    result = db.relationship('Result', backref='profile', lazy=True, cascade='all, delete-orphan')

class Result(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    stage = db.Column(db.String(120)) # Need to add the string, not the stage number
    rgb_val = db.Column(db.String(120)) # This is list but supposedly list of int can add as str
    days_since = db.Column(db.Integer)
    date_updated = db.Column(db.String(120))
    image = db.Column(db.String(12000))
    # Added new attributes
    leaf_l = db.Column(db.Integer)
    disease = db.Column(db.String(120))
    health_stat = db.Column(db.String(120))
    # Need a foreign key to associate the result with the profile
    profile_id = db.Column(db.Integer, db.ForeignKey('profile.id', ondelete='CASCADE'), nullable=False)
    # Newly added relationship.
    message = db.relationship('Message', backref='result', lazy=True, cascade='all, delete-orphan')

class Message(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(255))
    category = db.Column(db.String(120))
    # Newly added for relationship.
    result_id = db.Column(db.Integer, db.ForeignKey('result.id', ondelete='CASCADE'), nullable=False)
    cleared = db.Column(db.Boolean, default=False)

PaddyMonitoring/website/__init__.py
# Def create app and create database

from datetime import datetime
from flask import Flask
from os import path
from flask_sqlalchemy import SQLAlchemy
import os

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__, static_folder='static')
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    # New addition
    app.config['SESSION_PERMANENT'] = True  # Session data will be stored permanently
    db.init_app(app)
    # app.config['STATIC_URL_PATH'] = '/website/static'

    from .views import views
    from .analysis import analysis

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(analysis, url_prefix='/')

    # Assets Management
    app.config['ASSETS_ROOT'] = '/static/assets'
    # ASSETS_ROOT = os.getenv('ASSETS_ROOT', '/static/assets') 

    IMAGE_FOLDER = os.path.join('static', 'images')
    app.config['UPLOAD_FOLDER'] = IMAGE_FOLDER 

    # Add the custom filter to the Jinja2 environment
    app.jinja_env.filters['format_datetime'] = format_datetime
    app.jinja_env.filters['format_date'] = format_date
    
    with app.app_context():
        db.create_all()

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

def format_datetime(value):
    datetime_object = datetime.strptime(value, "%Y-%m-%d %H:%M:%S.%f")
    formatted_datetime = datetime_object.strftime("%d-%m-%Y %H:%M:%S")
    return formatted_datetime

def format_date(value):
    datetime_object = datetime.strptime(value, "%Y-%m-%d %H:%M:%S.%f")
    formatted_datetime = datetime_object.strftime("%d-%m-%Y")
    return formatted_datetime

PaddyMonitoring/website/views.py
from datetime import datetime
from flask import Blueprint, jsonify, render_template, request, redirect, session, url_for
from .models import Profile
from .models import Result
from .models import Message
from . import db
from datetime import datetime
from sqlalchemy import func
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.exc import NoResultFound

views = Blueprint('views', __name__)

# Function to fetch notifications
def get_notifications():
    return Message.query.filter_by(cleared=False).all()

# Context processor to add notifications to the context
@views.context_processor
def inject_notifications():
    return dict(notifications=get_notifications())

@views.route('/', methods=['POST', 'GET'])
def index():
    try:
        # Fetch each distinct profile along with its latest result
        profiles = (
            db.session.query(Profile, Result)
            .outerjoin(Result, Result.profile_id == Profile.id)
            .group_by(Profile.id)
            .order_by(Profile.id, Result.date_updated.desc())
            .distinct(Profile.id)
            .all()
        )

        return render_template('index.html', profiles=profiles)
    except NoResultFound as e:
        # Handle the case when no results are found
        profiles = Profile.query.all()
        return render_template('index.html', profiles=[])

@views.route('/profile/show', methods=['POST','GET'])
def display():
    profiles = Profile.query.all()
    return render_template('display.html',profiles=profiles)

@views.route('/profile', methods=['POST','GET'])
def plant_profile():
    if request.method == 'POST':
        date = request.form.get('initial_date')
        date_new = list(date.split("-"))
        y = int(date_new[0])
        m = int(date_new[1])
        d = int(date_new[2])
        name_plant = request.form.get('name_plant')
        type_plant = request.form.get('type_plant')
        device = request.form.get('device')
        new_profile = Profile(initial_date=datetime(y,m,d),name_plant=name_plant, type_plant=type_plant, device=device)
        db.session.add(new_profile)
        db.session.commit()
        print(new_profile)
        return redirect(url_for('views.display'))
    return render_template('profile.html')

@views.route('/profile/modify', methods=['POST','GET'])
def modify():
    profiles = Profile.query.all()
    return render_template('modify.html',profiles=profiles)

@views.route('/profile/modify/delete', methods=['POST','GET'])
def delete_profile():
    if request.method == 'POST':
        choice = request.form['choice']
        profile = Profile.query.filter(Profile.id == choice).first()
        db.session.delete(profile)
        db.session.commit()
        return redirect(url_for('views.modify'))
    return redirect(url_for('views.modify'))

@views.route('/notifications')
def notifications():

    # Retrieve messages with associated Result and Profile using outerjoin
    messages = Message.query \
        .filter_by(cleared=False) \
        .outerjoin(Result, Message.result_id == Result.id) \
        .outerjoin(Profile, Result.profile_id == Profile.id) \
        .options(joinedload(Message.result).joinedload(Result.profile)) \
        .all()
    
    # Fetch uncleared messages with associated Result and Profile
    uncleared_messages = Message.query \
        .filter_by(cleared=False) \
        .outerjoin(Result, Message.result_id == Result.id) \
        .outerjoin(Profile, Result.profile_id == Profile.id) \
        .options(joinedload(Message.result).joinedload(Result.profile)) \
        .all()

    # Fetch cleared messages with associated Result and Profile
    cleared_messages = Message.query \
        .filter_by(cleared=True) \
        .outerjoin(Result, Message.result_id == Result.id) \
        .outerjoin(Profile, Result.profile_id == Profile.id) \
        .options(joinedload(Message.result).joinedload(Result.profile)) \
        .all()

    return render_template('notifications.html', uncleared_messages=uncleared_messages, cleared_messages=cleared_messages)

@views.route('/clear_message/<int:message_id>', methods=['POST'])
def clear_message(message_id):
    message = Message.query.get_or_404(message_id)

    # Update the cleared attribute to True
    message.cleared = True
    db.session.commit()

    # Respond with a JSON indicating success
    return jsonify({'status': 'success'})

@views.route('/delete_notifications/<section>', methods=['POST'])
def delete_notification(section):
     # Update the specified messages with cleared=True based on the section
    if section == 'uncleared':
        messages = Message.query.filter_by(cleared=False).all()
    elif section == 'cleared':
        messages = Message.query.filter_by(cleared=True).all()
    else:
        return jsonify(success=False, error="Invalid section")

    if messages:
        for message in messages:
            db.session.delete(message)

        db.session.commit()

        return jsonify(success=True)
    else:
        return jsonify(success=False, error="No messages found in the specified section")

    
@views.route('/testing')
def test():
    latest_record = Result.query.order_by(Result.id.desc()).first()

    if latest_record:
        # Delete the latest record
        db.session.delete(latest_record)
        db.session.commit()
        print(f"Latest record deleted: {latest_record}")
    else:
        print("No records to delete.")
    
    return render_template('index.html')

PaddyMonitoring/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      Paddy Dashboard - {% block title %}{% endblock %} | Monitoring
    </title>
    <!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 11]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="description"
      content="Free Datta Able Admin Template come up with latest Bootstrap 4 framework with basic components, form elements and lots of pre-made layout options"
    />
    <meta
      name="keywords"
      content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"
    />
    <meta name="author" content="CodedThemes" />

    <!-- Favicon icon -->
    <link
      rel="icon"
      href="{{ config.ASSETS_ROOT }}/images/favicon.ico"
      type="image/x-icon"
    />
    <!-- fontawesome icon -->
    <link
      rel="stylesheet"
      href="{{ config.ASSETS_ROOT }}/fonts/fontawesome/css/fontawesome-all.min.css"
    />
    <!-- animation css -->
    <link
      rel="stylesheet"
      href="{{ config.ASSETS_ROOT }}/plugins/animation/css/animate.min.css"
    />
    <!-- vendor css -->
    <link rel="stylesheet" href="{{ config.ASSETS_ROOT }}/css/style.css" />
    <!-- dark mode css -->
    <link rel="stylesheet" href="{{ config.ASSETS_ROOT }}/css/dark.css" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}
  </head>
  <body>
    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
      <div class="loader-track">
        <div class="loader-fill"></div>
      </div>
    </div>
    <!-- [ Pre-loader ] End -->

    {% include 'includes/sidebar.html' %} {% include 'includes/navigation.html'
    %} {% block content %} {% endblock content %} {% include
    'includes/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}
    <script>
      $(document).ready(function () {
        $(".dropdown-toggle").dropdown();
      });
    </script>
    {% endblock javascripts %}
  </body>
</html>

PaddyMonitoring/website/templates/date.html
{% extends "base.html" %} {% block title %}Analysis{% endblock %} {% block
content %}
<div class="pcoded-main-container">
  <div class="pcoded-wrapper">
    <div class="pcoded-content">
      <div class="pcoded-inner-content">
        <div class="main-body">
          <div class="page-wrapper">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb custom-breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#"><i class="feather icon-home"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Analyse
                </li>
              </ol>
            </nav>
            <div class="row">
              <div class="col-sm-12">
                <div class="card">
                  <div class="card-header">
                    <h5>Choose Plant</h5>
                  </div>
                  <div class="card-block">
                    <h6>Choose the plant to be analysed in the form below.</h6>
                    <p style="color: red">
                      Note that the image file fetched will be of current date.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <form method="POST" align="center">
              {{ form.csrf_token }} {{ form.profile }} <br /><br />
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PaddyMonitoring/website/templates/display.html
{% extends "base.html" %} {% block title %}Plant Profile{% endblock %} {% block
content %}

<!-- [ Main Content ] start -->
<div class="pcoded-main-container">
  <div class="pcoded-wrapper">
    <div class="pcoded-content">
      <div class="pcoded-inner-content">
        <div class="main-body">
          <div class="page-wrapper">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb custom-breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#"><i class="feather icon-home"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Plant Profile
                </li>
              </ol>
            </nav>
            <br />
            {% if message %} {{ message }} {% endif %}
            <div class="card">
              <div class="card-header">
                <a
                  class="nav-item nav-link"
                  id="Profile"
                  href="/profile"
                  style="display: inline-block"
                  >Create new profile</a
                ><a
                  class="nav-item nav-link"
                  id="Delete"
                  href="/profile/modify"
                  style="display: inline-block"
                  >Delete profile</a
                >
                <span class="d-block m-t-5"></span>
              </div>
              <div class="text-dark mb-1">
                <div class="card-block table-border-style">
                  <div class="table-responsive">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th style="width: 3%"></th>
                          <th style="width: 32%">Name</th>
                          <th style="width: 20%">Date Planted</th>
                          <th style="width: 20%">Plant Type</th>
                          <th style="width: 20%">Device</th>
                        </tr>
                      </thead>
                      {% for profile in profiles %}
                      <div class="profile">
                        <tbody>
                          <tr>
                            <td></td>
                            <td>{{ profile.name_plant }}</td>
                            <td>
                              {{ profile.initial_date.strftime('%d-%m-%Y') }}
                            </td>
                            <td>{{ profile.type_plant }}</td>
                            {% if profile.device == 'Legume1' %}
                            <td>Long Bean Camera 1</td>
                            {% elif profile.device == 'Legume2' %}
                            <td>Long Bean Camera 2</td>
                            {% elif profile.device == 'Paddy1' %}
                            <td>Paddy Camera 1</td>
                            {% else %}
                            <td>Paddy Camera 2</td>
                            {% endif %}
                          </tr>
                        </tbody>
                      </div>
                      {% endfor %}
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PaddyMonitoring/website/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light">
  <div class="m-header">
    <a class="mobile-menu" id="mobile-collapse1" href="javascript:"
      ><span></span
    ></a>
    <a href="/" class="b-brand">
      <div class="b-bg">
        <i class="feather icon-trending-up"></i>
      </div>
      <span class="b-title">Datta Able</span>
    </a>
  </div>
  <a class="mobile-menu" id="mobile-header" href="javascript:">
    <i class="feather icon-more-horizontal"></i>
  </a>
  <div class="collapse navbar-collapse">
    <!-- This old -->
    <ul class="navbar-nav mr-auto">
      <li>
        <a
          href="javascript:"
          class="full-screen"
          onclick="javascript:toggleFullScreen()"
          ><i class="feather icon-maximize"></i
        ></a>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"
          >Dropdown</a
        >
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="/">Dashboard</a></li>
          <li>
            <a class="dropdown-item" href="/profile/show">Profiles</a>
          </li>
          <li>
            <a class="dropdown-item" href="/notifications">Notifications</a>
          </li>
        </ul>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li>
        <label>
          <i class="icon feather icon-sun" id="theme-indicator"></i>
          <input type="checkbox" id="theme-switch" class="d-none" />
        </label>
      </li>
      <li>
        <div class="dropdown">
          <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"
            ><i class="icon feather icon-bell"></i
          ></a>
          <div class="dropdown-menu dropdown-menu-right notification">
            <div class="noti-head">
              <h6 class="d-inline-block m-b-0">Notifications</h6>
              <div class="float-right">
                <a href="javascript:" class="m-r-10">mark as read</a>
                <a href="/clear_notifications">clear all</a>
              </div>
            </div>
            <ul class="noti-body">
              {% for notification in notifications %}
              <li class="n-title">
                <p class="m-b-0">NEW</p>
              </li>
              <li class="notification">
                <div class="media">
                  <div class="media-body">
                    <!-- Notification section -->
                    <p>{{ notification.text }}</p>
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>
            <div class="noti-footer">
              <a href="/notifications">show all</a>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</header>
<!-- [ Header ] end -->

PaddyMonitoring/website/templates/includes/scripts.html
<script src="{{ config.ASSETS_ROOT }}/js/vendor-all.min.js"></script>
<script src="{{ config.ASSETS_ROOT }}/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="{{ config.ASSETS_ROOT }}/js/pcoded.min.js"></script>
<script src="{{ config.ASSETS_ROOT }}/js/dark-mode.js"></script>

PaddyMonitoring/website/templates/modify.html
{% extends "base.html" %} {% block title %}Modify{% endblock %} {% block content
%}
<div class="pcoded-main-container">
  <div class="pcoded-wrapper">
    <div class="pcoded-content">
      <div class="pcoded-inner-content">
        <div class="main-body">
          <div class="page-wrapper">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb custom-breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#"><i class="feather icon-home"></i></a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{{ url_for('views.display') }}">Plant Profile</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Delete Profile
                </li>
              </ol>
            </nav>
            <div class="container">
              <div class="row">
                <div class="col-sm-12">
                  <div class="card">
                    <div class="card-body">
                      <h5>Select profile to delete.</h5>
                      <a href="/profile/show">Back</a><br />
                      <hr />

                      <form
                        method="POST"
                        id="plants"
                        action="{{ url_for('views.delete_profile') }}"
                      >
                        <div class="text-dark mb-1">
                          <table class="table">
                            <thead>
                              <tr>
                                <th></th>
                                <th style="width: 35%">Name</th>
                                <th style="width: 20%">Date Planted</th>
                                <th style="width: 20%">Plant Type</th>
                                <th style="width: 20%">Device</th>
                              </tr>
                            </thead>
                            {% for profile in profiles %}
                            <div class="profile">
                              <tbody>
                                <tr>
                                  <td class="center-align">
                                    <input
                                      type="radio"
                                      name="choice"
                                      value="{{ profile.id }}"
                                      required
                                    />
                                  </td>
                                  <td>{{ profile.name_plant }}</td>
                                  <td>
                                    {{ profile.initial_date.strftime('%d-%m-%Y')
                                    }}
                                  </td>
                                  <td>{{ profile.type_plant }}</td>
                                  {% if profile.device == 'Legume1' %}
                                  <td>Long Bean Camera 1</td>
                                  {% elif profile.device == 'Legume2' %}
                                  <td>Long Bean Camera 2</td>
                                  {% elif profile.device == 'Paddy1' %}
                                  <td>Paddy Camera 1</td>
                                  {% else %}
                                  <td>Paddy Camera 2</td>
                                  {% endif %}
                                </tr>
                              </tbody>
                            </div>
                            {% endfor %}
                          </table>
                          <br />
                          <div align="center">
                            <p>Are you sure you want to delete this profile?</p>

                            <div
                              class="form-check"
                              style="display: inline-block"
                            >
                              <label class="form-check-label"
                                ><input
                                  class="form-check-input"
                                  type="radio"
                                  name="confirm"
                                  value="delete"
                                  required
                                />Yes</label
                              >
                            </div>
                          </div>
                        </div>
                        <br />
                        <div class="form-group" align="center">
                          <input
                            class="btn btn-danger"
                            type="submit"
                            value="Confirm"
                          />
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PaddyMonitoring/website/templates/option.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} {% block
content %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<div class="pcoded-main-container">
  <div class="pcoded-wrapper">
    <div class="pcoded-content">
      <div class="pcoded-inner-content">
        <div class="main-body">
          <div class="page-wrapper">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb custom-breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#"><i class="feather icon-home"></i></a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{{ url_for('views.index') }}">Paddy</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{{ url_for('analysis.display_dash') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Choose Date
                </li>
              </ol>
            </nav>
            <h3 align="center">Display Dashboard</h3>
            <form
              method="POST"
              action="{{ url_for('analysis.dashboard_option') }}"
            >
              {{ form.csrf_token }}
              <label for="profile">Profile:</label>
              {{ form.profile(class="form-control", id="profile") }}

              <label for="result_date">Result Date:</label>
              <select
                name="result_date"
                id="result_date"
                class="form-control"
              ></select>
              <!-- Result date input using flatpickr -->
              <!-- <label for="result_date">Select Result Date:</label>
              <input
                type="text"
                id="result_date"
                name="result_date"
                placeholder="Select Date"
              /> -->

              <button type="submit">Submit</button>
            </form>
            <script>
              $(document).ready(function () {
                // Set up an event listener for the profile dropdown change
                $("#profile").change(function () {
                  var profile_id = $(this).val();

                  // Check if a profile ID is selected
                  if (profile_id) {
                    // Make an AJAX request to fetch result date choices based on the selected profile
                    $.ajax({
                      type: "GET",
                      url: "/get_result_dates/" + profile_id,
                      success: function (data) {
                        console.log("Received data:", data);

                        // Clear existing options
                        $("#result_date").empty();

                        // Append each option to the dropdown
                        data.forEach(function (result) {
                          if (
                            result.id !== undefined &&
                            result.date_updated !== undefined
                          ) {
                            // Use result.profile_id as the option value
                            // Display result.date_updated in the dropdown
                            $("#result_date").append(
                              '<option value="' +
                                result.id +
                                '">' +
                                result.date_updated +
                                "</option>"
                            );
                          } else {
                            console.warn("Skipping invalid result:", result);
                          }
                        });

                        console.log(
                          "Dropdown HTML after update:",
                          $("#result_date").html()
                        );
                      },
                    });
                  } else {
                    // No profile ID selected, clear the result_date dropdown
                    $("#result_date").empty();
                  }
                });
              });
            </script>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}